### ISSUE TITLE
Clean up repository a bit

### ISSUE THREAD

**Issue by electricjones** [ravenfire/magpie#1]
Let's remove the following files from being tracked:
- [x] .idea
- [x] composer.phar

**Comment by JamesRichards07** [comment]
I don't see the .idea file. Is this something we would be adding later?

**Comment by electricjones** [comment]
The `.idea` folder is a hidden folder. Any folder/file that starts with `.` is hidden. The `.idea` folder holds the configuration stuff for your phpstorm for that project. It's not something that is usually added because each person's configuration will be different.

You should be able to see it in a terminal (either phpstorm's or your computer's) with `ls -a`. the `-a` stands for `all`. And it will show even hidden files/folders.
