### ISSUE TITLE
Some Code Review Suggestions

### ISSUE THREAD

**Issue by electricjones** [ravenfire/magpie#2]
These are just some working ideas as I look through the code. Some of them are specific to recent commits, others are just general ideas as we continue building the project.

These are the kind of comments I would normally do in a PR, which is what we have agreed to do moving forward.

- [x] Maybe we can come up with a better naming for the classes. For instance https://github.com/ravenfire/magpie/blob/d6c1ed5ee00916c6dec469e053bd29333b6580e3/src/Ravenfire/BoardGameGeek.php#L9 could probably be `BoardGameGeekSource` to make it clearer. Same for the models and migrations. Maybe just append what the class actually is to each?
- [x] Please add docblocks to the classes themselves. 
- [x] Eventually, we may want to reorder the methods in the classes themselves so the required methods are up top. For example, it probably makes sense for the `execute()` method on `BoardGameGeek` to be the first method.
- [x] Anytime you log in the `BoardGameGeek` class, use the `$this->` like you do at https://github.com/ravenfire/magpie/blob/d6c1ed5ee00916c6dec469e053bd29333b6580e3/src/Ravenfire/BoardGameGeek.php#L47 instead of the static call `BoardGameGeek::notice()`, etc
- [x] Same with the save() method here https://github.com/ravenfire/magpie/blob/master/src/Ravenfire/BoardGameGeek.php#L188. Use `$this->`. Probably worth doing a basic check for `::` to make sure the methods you call using that static operator are actually static.
- [x] I like how simple the `execute()` method is. Good job 
- [x] I think we want two sub namespaces inside `Ravenfire` to keep the primary entity and the various sources separate. So, maybe, all the game stuff goes in `Ravenfire\Games` and the BGG stuff goes in `Ravenfire\BoardGameGeek`.

Overall, this is good work -- especially for the time frame you worked in. I look forward to moving forward. Thanks for the hard work.

**Comment by JamesRichards07** [comment]
When adding docblocks to the classes I'm not being very creative or detailed. i.e. BoardGameGeekMigration - "Details table information for the BoardGameGeekModel."

Also, I wasn't sure how to reference my code like you did above.

**Comment by electricjones** [comment]
Yeah, no need to be super creative for the classes. Just a hint for future us.
To reference code on github.com you have to push your branch, switch to that branch, and then find the code you want to reference. Anytime you are looking at code you can click on the numbers along the left and get a link to that line. When you paste that link into a github textbox, usually it will do automagic stuff.
