### ISSUE TITLE
Check for updates on Board Game Geek data.

### ISSUE THREAD

**Issue by JamesRichards07** [ravenfire/magpie#4]
These are my thoughts on next logical steps for improving Magpie.

- [x] Remove early returns when game data already exists.
- [x] Add a feature to check for updated Board Game Geek data.
- [x] Replace data on the boardgamegeek table with updated information.
- [ ] Verify audit table is saving both the old and new boardgamegeek data.
- [ ] Update `AuditTableMigration`

**Comment by electricjones** [comment]
This is a great scope for this ticket. I was thinking that (at least for now) we don't need to have multiple `board_game_geek` table records. Just update the one and keep an audit trail.

I added a task to this. I didn't actually finish the `AuditTableMigration`, so you will need to add some columns to track what actually changed.

I'll let you decide how that works, but there are two basic approaches we can take:
1. A single audit record per *game* that has changed. So, that one record would have to track if two different bgg fields changed on that run
2. A single audit record per *change*. So, if the game's runtime and recommended players changed, we would create 2 audit records. 1 for each change.

If you want to discuss that more, we certainly can.

Also, remember we decided to do this work in the `AbstractSource->save()` method. We always just want the sources to give us a fully populated model and Magpie decides what needs saved and what audit records need created.
